"""add_is_test_column

Revision ID: 983340fff470
Revises: 0001
Create Date: 2026-08-13 14:12:09.257351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983340fff470'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_constraint('applications_resume_version_id_fkey', 'applications', type_='foreignkey')
    op.drop_constraint('applications_job_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'jobs_raw', ['job_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'resume_versions', ['resume_version_id'], ['id'])
    op.alter_column('contacts', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'company',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'linkedin_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'email_confidence',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'website',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('contacts_job_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'jobs_raw', ['job_id'], ['id'])
    op.alter_column('dork_queries', 'query_template',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dork_queries', 'target_group',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('dork_queries', 'role_keyword_source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'resume_profile.target_roles'::text"))
    op.alter_column('job_scores', 'rationale',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('job_scores_job_id_fkey', 'job_scores', type_='foreignkey')
    op.create_foreign_key(None, 'job_scores', 'jobs_raw', ['job_id'], ['id'])
    op.add_column('jobs_raw', sa.Column('is_test', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('jobs_raw', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('jobs_raw', 'source_job_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jobs_raw', 'source_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jobs_raw', 'company',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('jobs_raw', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('jobs_raw', 'description_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('jobs_raw', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jobs_raw', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'discovered'::text"))
    op.drop_index('ix_jobs_raw_discovered_at', table_name='jobs_raw')
    op.drop_index('ix_jobs_raw_source_tier', table_name='jobs_raw')
    op.drop_index('ix_jobs_raw_status', table_name='jobs_raw')
    op.alter_column('outreach_drafts', 'channel',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('outreach_drafts', 'draft_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('outreach_drafts_job_id_fkey', 'outreach_drafts', type_='foreignkey')
    op.drop_constraint('outreach_drafts_contact_id_fkey', 'outreach_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'outreach_drafts', 'jobs_raw', ['job_id'], ['id'])
    op.create_foreign_key(None, 'outreach_drafts', 'contacts', ['contact_id'], ['id'])
    op.alter_column('resume_versions', 'pdf_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('resume_versions', 'model_used',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('resume_versions_job_id_fkey', 'resume_versions', type_='foreignkey')
    op.create_foreign_key(None, 'resume_versions', 'jobs_raw', ['job_id'], ['id'])
    op.alter_column('settings', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('source_health', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('source_health', 'last_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('target_companies', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('target_companies', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('target_companies', 'careers_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('target_companies', 'detected_ats',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_companies', 'detected_ats',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('target_companies', 'careers_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('target_companies', 'domain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('target_companies', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('source_health', 'last_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('source_health', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('settings', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'resume_versions', type_='foreignkey')
    op.create_foreign_key('resume_versions_job_id_fkey', 'resume_versions', 'jobs_raw', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('resume_versions', 'model_used',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('resume_versions', 'pdf_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'outreach_drafts', type_='foreignkey')
    op.drop_constraint(None, 'outreach_drafts', type_='foreignkey')
    op.create_foreign_key('outreach_drafts_contact_id_fkey', 'outreach_drafts', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('outreach_drafts_job_id_fkey', 'outreach_drafts', 'jobs_raw', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('outreach_drafts', 'draft_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('outreach_drafts', 'channel',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_jobs_raw_status', 'jobs_raw', ['status'], unique=False)
    op.create_index('ix_jobs_raw_source_tier', 'jobs_raw', ['source_tier'], unique=False)
    op.create_index('ix_jobs_raw_discovered_at', 'jobs_raw', ['discovered_at'], unique=False)
    op.alter_column('jobs_raw', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'discovered'::text"))
    op.alter_column('jobs_raw', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs_raw', 'description_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('jobs_raw', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('jobs_raw', 'company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('jobs_raw', 'source_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs_raw', 'source_job_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs_raw', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('jobs_raw', 'is_test')
    op.drop_constraint(None, 'job_scores', type_='foreignkey')
    op.create_foreign_key('job_scores_job_id_fkey', 'job_scores', 'jobs_raw', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('job_scores', 'rationale',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dork_queries', 'role_keyword_source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'resume_profile.target_roles'::text"))
    op.alter_column('dork_queries', 'target_group',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dork_queries', 'query_template',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_job_id_fkey', 'contacts', 'jobs_raw', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('contacts', 'website',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'email_confidence',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'linkedin_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_job_id_fkey', 'applications', 'jobs_raw', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('applications_resume_version_id_fkey', 'applications', 'resume_versions', ['resume_version_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.alter_column('applications', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('applications', 'method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
